<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BoatData extends Model
{
    use HasFactory;
    protected $table = "boatdata";

    protected $fillable = [
        'mac',
        'val',
        'lat',
        'ns',
        'lon',
        'ew',
        'sog',
        'cog',
        'dog',
        'altitude',
        'utc',
        'date',
        'aws',
        'awa',
        'dep',
        'hdg',
        'spd',
        'mtw',
        'dist',
        'tdist',
        'wprange',
        'wpbearing',
        'wpvelocity',
        'wpxte',
        'wpid',
        'wplat',
        'wplon',
        'rpm1',
        'boost1',
        'tilt1',
        'oilp1',
        'oilt1',
        'coolt1',
        'altv1',
        'fuelr1',
        'coolp1',
        'load1',
        'torq1',
        'rpm2',
        'boost2',
        'tilt2',
        'oilp2',
        'oilt2',
        'coolt2',
        'altv2',
        'fuelr2',
        'coolp2',
        'load2',
        'torq2',
        'rudder',
        'pitch',
        'roll',
        'yaw',
        'xacc',
        'yacc',
        'zacc',
        'voltint1',
        'voltint2',
        'voltnmea',
        'voltn2k',
        'bar',
        'temp',
        'tempext',
        'tank1',
        'tank2',
        'tank3',
        'tank4',
        'f1',
        'f2',
        'f3',
        'f4',
        'f5',
        'f6',
        'sats',
        'hdop',
        'gps',
        'uptime',
        'dbtime',
        'dog_nm',
        'eng1_econ',
        'eng2_econ',
        'tws',
        'twa',
        'vmg',
        'gws',
        'gwa',
        'gvmg',
        'latdec',
        'londec',
        'datetime',
    ];
}
